### ISSUE TITLE
Problema de cache de consulta no rethink

### ISSUE THREAD

**Issue by claytonsilva** [xdevelsistemas/js-data-dao#3]
Conforme relatado por @alvarollmenezes , houve caso de consulta vir resposta não condizente com o resultado da query. 

@alvarollmenezes se possível relatar uns passos para reproduzirmos

**Comment by alvarollmenezes** [comment]
Estava testando aqui e acredito que não seja um PROBLEMA em si. 

Acontece se você alterar algo direto no banco (ou por outro meio que não seja o datastore do jsdata). Dessa forma o jsdata não vai ao banco verificar se algo mudou, parece que ele "confia" no datastore.

**Comment by claytonsilva** [comment]
Estou fechando o caso, no caso iremos por enquanto ignorar que atualizacoes externas interfiram no modelo
