### ISSUE TITLE
Documentação da lib

### ISSUE THREAD

**Issue by mikaelhadler** [xdevelsistemas/js-data-dao#31]
Prezados, 

Seria possível disponibilizar a documentação no README.md ?

**Comment by davidpvilaca** [comment]
@claytonsilva 
Relevant issue. **Duplicate** #30 

### _Suggestion_:

README.md -> Project basics.
Github Wiki -> Complete documentation.

**Comment by claytonsilva** [comment]
@mikaelhadler vou fechar essa issue pra tratar na issue #30
