### ISSUE TITLE
Verificar necessidade de parseModel na classe DAO

### ISSUE THREAD

**Issue by vizeke** [xdevelsistemas/js-data-dao#5]
Se não for necessário, remover a função abaixo da classe models/DAO

public parseModel ( val: any ): T {
    throw new Error( 'not implemented' )
}

Se por algum motivo existir a necessidade de manter essa função. Alterar a mensagem de erro para "parseModel not implemented"

@alvarollmenezes

**Comment by claytonsilva** [comment]
Vou verificar, se não me engano deveria jogar o erro da não implementação da mesma.

**Comment by claytonsilva** [comment]
duplicado com o item #9

**Comment by claytonsilva** [comment]
Engano , vou colocar a implementação e eliminar a necessidade na versao 2.1.0
